import os
path0=os.getcwd()
phosT="phosData/Tprocessed.json"
phosT2="phosData/Tprocessed2.json"

raw3="phosData/rawdataprocessed3.json"
phosT_nodecoration="phosData/TprocessedTrue.json"
phosT_decoration="phosData/TprocessedFalse.json"
hela2charge3="DeepdiaData/6932/HF_2585_HeLa_charge3.ions/HF_2585_HeLa_charge3.ions.json"
hela1charge3="DeepdiaData/5573/HF_HeLa_charge3.ions/HF_HeLa_charge3.ions.json"
phosTcharge1="phosData/Tcharge1.json"
phosTcharge2="phosData/Tcharge2.json"
phosTcharge3="phosData/Tcharge3.json"
phosTcharge4="phosData/Tcharge4.json"
phosTcharge5="phosData/Tcharge5.json"
phosTcharge6="phosData/Tcharge6.json"
phosTcharge7="phosData/Tcharge7.json"
phosTcharge8="phosData/Tcharge8.json"

phosT2charge1="phosData/Tprocessed21.json"
phosT2charge2="phosData/Tprocessed22.json"
phosT2charge3="phosData/Tprocessed23.json"
phosT2charge4="phosData/Tprocessed24.json"
phosT2charge5="phosData/Tprocessed25.json"
phosT2charge6="phosData/Tprocessed26.json"
phosT2charge7="phosData/Tprocessed27.json"
phosT2charge8="phosData/Tprocessed28.json"
phosT2_nodecoration="phosData/Tprocessed2True.json"
phosT2_decoration="phosData/Tprocessed2False.json"

raw1="phosData/rawdataprocessed.json"
raw2="phosData/rawdataprocessed2.json"
phosTaddon="phosData/rawdataprocessed.json"
irtall="phosData/irtprocessedstdall.json"
irtstd1="phosData/irtprocessed<=1.json"
irtstd2="phosData/irtprocessed<=2.json"
DDALIB="DDAtestData/DDALIBRARY3processed.json"
DDALIBALL="DDAtestData/DDALIBRARYALLprocessed.json"
allphosT="AllphosT/Tprocessed2.json"
allphosTpnumber1="AllphosT/Tprocessed2pnumber1.json"
allirtphosTstd2="AllphosTirt/irtprocessed<=2.json"
targetjpt="synthetic/JPT_DDA_newsynfasta.csv"
targetsigma="synthetic/syntheticpep_Sigma_pycharm_monophos_412.csv"
directdia="direct_DIA/direct_DIA_mono_pro_pycharm_phos_charge23.csv"
FDR="FDR/synFDR.csv"
stydecoy="STYdecoy/stydecoy.csv"
fangansan="FDR/fangansan1.csv"
fangansanad="FDR/fangansan_alldecoy.csv"
fangansan5="FDR/fangansan12021_5_28.csv"

JPR="JPR/20200531_152317_JPR_cos_Fragment Report_20200531_153515processed.json"
FDR2="FDR2/synFDR2.csv"
FinalJPT="FinalJPT/20200418_124926_JPT_quchunon-phosprocessed.json"
FinalJPT1="FinalJPT/20200418_124926_JPT_quchunon-phos(1)processed.json"
REALup2="FDR/Real/real_sample_2021520_phosup2.csv"
REAL1="FDR/Real/real_sample_2021520——phos1.csv"
REAL2="FDR/Real/real_sample_2021520_phos2.csv"
JPST="JPST/JPST2021_6_1.csv"
newdecoy2021621="FDR/2021621_newdecoy.csv"